# This is a basic workflow to help you get started with Actions

name: hais_build

on:
  workflow_dispatch:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'https://hugeota.d.miui.com/21.10.13/miui_PICASSO_21.10.13_6c3b6adae1_11.0.zip'
  ZIP_NAME: 'miui.zip'
  upload_WeTransfer: 'true'
  SETUP: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git wget git zip unzip curl axel

       - name: Cloning...
         run: |
             git clone https://github.com/buihien224/hais-github-action.git $GITHUB_WORKSPACE/hais-github-action
           
       - name: Download zip...
         run: |
            cd $GITHUB_WORKSPACE/hais-github-action
            axel -n $(nproc) -U "Mozilla/5.0" $ROM_URL -o "$GITHUB_WORKSPACE/hais-github-action/$ZIP_NAME" || wget -U "Mozilla/5.0" $ROM_URL -O "$GITHUB_WORKSPACE/hais-github-action/$ZIP_NAME"
            echo "zip_file: $(ls "$GITHUB_WORKSPACE/hais-github-action/")"
            
       - name: Setup Tool Utils...
         run: |
            cd $GITHUB_WORKSPACE/hais-github-action
            ls
            sudo bash $GITHUB_WORKSPACE/hais-github-action/Bin/1.Install.sh 
            ls -l
       - name: Building Cái gì còn lâu mới nói...
         run: |
            cd $GITHUB_WORKSPACE/hais-github-action
            ls            
            sudo bash $GITHUB_WORKSPACE/hais-github-action/HaisAuto.sh $ZIP_NAME
            ls -l

       - name: Upload Hais Build to WeTransfer...
         if: env.upload_WeTransfer == 'true' 
         run: |
           cd $GITHUB_WORKSPACE/hais-github-action
           ls
           cd output
           ls 
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ./$REPACK_NAME         
